# Generated by Django 5.2.17 on 2026-09-26 18:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaccion',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='gestion.cliente'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuenta',
            name='n_cuenta',
            field=models.CharField(default=None, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuenta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='tipo_cuenta',
            field=models.CharField(choices=[('CUENTA_AHORRO', 'cuenta ahorro'), ('CUENTA_CORRIENTE', 'cuenta corriente'), ('CUENTA_VISTA', 'cuenta vista')], default=None, max_length=25),
            preserve_default=False,
        ),
    ]
