# Generated by Django 5.2.17 on 2026-09-30 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_cuenta', models.CharField(max_length=50, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_cuenta', models.CharField(choices=[('CUENTA_AHORRO', 'cuenta ahorro'), ('CUENTA_CORRIENTE', 'cuenta corriente'), ('CUENTA_VISTA', 'cuenta vista')], max_length=25)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='gestion.cliente')),
            ],
        ),
    ]
