# Generated by Django 5.2.17 on 2026-09-26 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_delete_transaccion_cuenta_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, max_length=300, null=True)),
                ('tipo_transaccion', models.CharField(choices=[('TRANSFERENCIA', 'transferencia'), ('RETIRO', 'retiro'), ('DEPOSITO', 'deposito')], max_length=35)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='gestion.cuenta')),
            ],
        ),
    ]
