# Generated by Django 5.2.17 on 2026-10-01 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelo', models.CharField(choices=[('NEGRO', 'negro'), ('RUBIO', 'rubio'), ('CAFE', 'cafe'), ('OTRO', 'otro')], max_length=50)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
            ],
        ),
    ]
