# Generated by Django 5.2.17 on 2026-09-27 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='gestion.cliente'),
            preserve_default=False,
        ),
    ]
