# Generated by Django 5.2.17 on 2026-10-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.IntegerField()),
                ('cliente', models.ManyToManyField(blank=True, related_name='promociones', to='gestion.cliente')),
            ],
        ),
    ]
