# Generated by Django 5.2.17 on 2026-09-29 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_cuenta_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descuento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelo', models.CharField(choices=[('NEGRO', 'negro'), ('RUBIO', 'rubio'), ('CAFE', 'cafe'), ('OTRO', 'otro')], max_length=50)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='promocion',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='gestion.promocion'),
        ),
    ]
